cursor #ebe1d4
cursor_text_color #d0c5b4

foreground            #ebe1d4
background            #17130b
selection_foreground  #3a2f15
selection_background  #d7c5a0
url_color             #e7c26c

color0   #17130b
color1   #ff7669
color2   #7ee76c
color3   #ffe669
color4   #dbb14f
color5   #6a4b02
color6   #e7c26c
color7   #f2ede3
color8   #96928a
color9   #ffa199
color10  #aeff9f
color11  #ffef9f
color12  #fedb8b
color13  #ffe29f
color14  #ffecc1
color15  #fffcf8
