cursor #e4e3d7
cursor_text_color #c7c8b8

foreground            #e4e3d7
background            #13140d
selection_foreground  #2d331c
selection_background  #c4caa9
url_color             #bccf81

color0   #13140d
color1   #ee7e6b
color2   #71cf67
color3   #ffea72
color4   #aec46b
color5   #4f5f1d
color6   #bccf81
color7   #d6d9cc
color8   #84867c
color9   #ffad9f
color10  #a9f8a1
color11  #fff2a5
color12  #d1e39a
color13  #eeffbb
color14  #f4ffd3
color15  #fdfff8
