include dank-tabs.conf
include dank-theme.conf
window_padding_width 5
hide_window_decorations yes
background_opacity 0.8
font_family Monaco
# font_family JetBrains Maple Mono
font_size 13.5
# font_size 18
remember_window_size no
confirm_os_window_close 0
shell zsh
cursor_trail 1 
cursor_shape block
shell_integration no-cursor

